-- PCB Quotes Table for Supabase
create table if not exists public.pcb_quotes (
  id bigint generated by default as identity primary key,
  pcbType text,
  layers integer,
  thickness text,
  hdi text,
  tg text,
  panelCount integer,
  shipmentType text,
  singleLength numeric,
  singleWidth numeric,
  singleCount integer,
  border text,
  surfaceFinish text,
  copperWeight text,
  minTrace text,
  minHole text,
  solderMask text,
  silkscreen text,
  goldFingers text,
  castellated text,
  impedance text,
  flyingProbe text,
  quantity integer,
  delivery text,
  gerber text,
  maskCover text,
  edgePlating text,
  halfHole text,
  edgeCover text,
  testMethod text,
  prodCap text,
  productReport jsonb,
  rejectBoard text,
  yyPin text,
  customerCode text,
  payMethod text,
  qualityAttach text,
  smt text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 收货地址表
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  country text not null,
  state text,
  city text,
  zip text,
  address text not null,
  phone text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 报关信息表
create table if not exists public.customs_declarations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  declaration_method text not null,
  company_name text,
  tax_id text,
  personal_id text,
  incoterm text,
  purpose text,
  declared_value numeric,
  customs_note text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 订单主表
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  address_id bigint references addresses(id),
  customs_id bigint references customs_declarations(id),
  pcb_spec jsonb not null,
  gerber_file_url text,
  courier text,
  price numeric,
  shipping_cost numeric,
  customs_fee numeric,
  total numeric,
  pcb_note text,
  user_note text,
  status text default 'pending',
  admin_price numeric, -- 管理员审核后可填写
  admin_note text,     -- 管理员审核备注
  created_at timestamp with time zone default timezone('utc'::text, now())
);
