import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import { UserProvider } from "@/lib/UserContext";
import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";
import { cookies, headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // SSR 获取用户
  const supabase = createPagesServerClient({ cookies, headers });
  const { data: { user } } = await supabase.auth.getUser();

  // 只传递基础字段，兼容 UserProvider 类型
  const safeUser = user
    ? {
        id: user.id,
        email: user.email,
        aud: user.aud,
        role: user.role,
        // 可根据 ExtendedUser 类型补充其它字段
      }
    : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider initialUser={safeUser}>
          <Navbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
