export const serviceTypeMultipliers = {
  express: 1.2,
  standard: 1.0,
  economy: 0.8,
};

export const shippingZones = [
  {
    zone: 'Zone 1 - East & Southeast Asia',
    countries: ['jp', 'kr', 'sg', 'my', 'th', 'vn', 'ph', 'id'],
    dhl: {
      baseRate: 15,
      pricePerKg: 4.5,
      fuelSurcharge: 0.18,
      peak: 0.1,
      deliveryTime: '2-4 business days',
    },
    fedex: {
      baseRate: 16,
      pricePerKg: 4.8,
      fuelSurcharge: 0.19,
      peak: 0.12,
      deliveryTime: '2-5 business days',
    },
    ups: {
      baseRate: 17,
      pricePerKg: 5.0,
      fuelSurcharge: 0.19,
      peak: 0.11,
      deliveryTime: '3-5 business days',
    },
  },
  {
    zone: 'Zone 2 - North America',
    countries: ['us', 'ca', 'mx'],
    dhl: {
      baseRate: 22,
      pricePerKg: 6.5,
      fuelSurcharge: 0.20,
      peak: 0.15,
      deliveryTime: '3-5 business days',
    },
    fedex: {
      baseRate: 21,
      pricePerKg: 6.2,
      fuelSurcharge: 0.22,
      peak: 0.16,
      deliveryTime: '3-6 business days',
    },
    ups: {
      baseRate: 20,
      pricePerKg: 6.0,
      fuelSurcharge: 0.21,
      peak: 0.15,
      deliveryTime: '4-7 business days',
    },
  },
  {
    zone: 'Zone 3 - Europe',
    countries: ['gb', 'de', 'fr', 'it', 'es', 'nl', 'be', 'ch', 'se', 'no', 'dk', 'fi', 'pl', 'at', 'ie'],
    dhl: {
      baseRate: 24,
      pricePerKg: 7.0,
      fuelSurcharge: 0.22,
      peak: 0.15,
      deliveryTime: '3-5 business days',
    },
    fedex: {
      baseRate: 26,
      pricePerKg: 7.5,
      fuelSurcharge: 0.23,
      peak: 0.16,
      deliveryTime: '3-6 business days',
    },
    ups: {
      baseRate: 25,
      pricePerKg: 7.2,
      fuelSurcharge: 0.22,
      peak: 0.15,
      deliveryTime: '4-6 business days',
    },
  },
  {
    zone: 'Zone 4 - Australia & New Zealand',
    countries: ['au', 'nz'],
    dhl: {
      baseRate: 28,
      pricePerKg: 8.0,
      fuelSurcharge: 0.21,
      peak: 0.15,
      deliveryTime: '3-6 business days',
    },
    fedex: {
      baseRate: 30,
      pricePerKg: 8.2,
      fuelSurcharge: 0.22,
      peak: 0.16,
      deliveryTime: '4-7 business days',
    },
    ups: {
      baseRate: 29,
      pricePerKg: 8.1,
      fuelSurcharge: 0.21,
      peak: 0.15,
      deliveryTime: '5-8 business days',
    },
  },
  {
    zone: 'Zone 5 - Middle East & India',
    countries: ['ae', 'sa', 'qa', 'kw', 'in'],
    dhl: {
      baseRate: 32,
      pricePerKg: 9.0,
      fuelSurcharge: 0.23,
      peak: 0.18,
      deliveryTime: '4-7 business days',
    },
    fedex: {
      baseRate: 35,
      pricePerKg: 9.5,
      fuelSurcharge: 0.24,
      peak: 0.20,
      deliveryTime: '4-8 business days',
    },
    ups: {
      baseRate: 34,
      pricePerKg: 9.2,
      fuelSurcharge: 0.23,
      peak: 0.19,
      deliveryTime: '6-10 business days',
    },
  },
  {
    zone: 'Zone 6 - South America & Africa (Remote)',
    countries: ['br', 'za', 'ar', 'cl', 'ng'],
    dhl: {
      baseRate: 40,
      pricePerKg: 12.0,
      fuelSurcharge: 0.25,
      peak: 0.20,
      deliveryTime: '6-10 business days',
    },
    fedex: {
      baseRate: 42,
      pricePerKg: 12.5,
      fuelSurcharge: 0.26,
      peak: 0.22,
      deliveryTime: '6-10 business days',
    },
    ups: {
      baseRate: 41,
      pricePerKg: 12.2,
      fuelSurcharge: 0.25,
      peak: 0.21,
      deliveryTime: '7-12 business days',
    },
  },
  {
    zone: 'other',
    countries: [], // Other countries
    dhl: {
      baseRate: 45,
      pricePerKg: 11.0,
      fuelSurcharge: 0.25,
      peak: 0.22,
      deliveryTime: '7-12 business days',
    },
    fedex: {
      baseRate: 48,
      pricePerKg: 11.5,
      fuelSurcharge: 0.26,
      peak: 0.24,
      deliveryTime: '7-12 business days',
    },
    ups: {
      baseRate: 46,
      pricePerKg: 11.2,
      fuelSurcharge: 0.25,
      peak: 0.23,
      deliveryTime: '8-14 business days',
    },
  },
]; 